<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Inspire Me ✨ - Daily Motivation</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet">
  
  <style>
    body {
      box-sizing: border-box;
      font-family: 'Inter', sans-serif;
    }
    
    .gradient-bg {
      background: linear-gradient(-45deg, #667eea, #764ba2, #f093fb, #f5576c, #4facfe, #00f2fe);
      background-size: 400% 400%;
      animation: gradientShift 15s ease infinite;
    }
    
    @keyframes gradientShift {
      0% { background-position: 0% 50%; }
      50% { background-position: 100% 50%; }
      100% { background-position: 0% 50%; }
    }
    
    .floating-particles {
      position: absolute;
      width: 100%;
      height: 100%;
      overflow: hidden;
      pointer-events: none;
    }
    
    .particle {
      position: absolute;
      background: rgba(255, 255, 255, 0.1);
      border-radius: 50%;
      animation: float 20s infinite linear;
    }
    
    @keyframes float {
      0% {
        transform: translateY(100vh) rotate(0deg);
        opacity: 0;
      }
      10% {
        opacity: 1;
      }
      90% {
        opacity: 1;
      }
      100% {
        transform: translateY(-100px) rotate(360deg);
        opacity: 0;
      }
    }
    
    .quote-card {
      background: rgba(255, 255, 255, 0.95);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(255, 255, 255, 0.2);
      box-shadow: 0 25px 50px rgba(0, 0, 0, 0.1);
      transition: all 0.5s cubic-bezier(0.4, 0, 0.2, 1);
    }
    
    .quote-card:hover {
      transform: translateY(-10px);
      box-shadow: 0 35px 70px rgba(0, 0, 0, 0.15);
    }
    
    .quote-text {
      font-family: 'Playfair Display', serif;
      line-height: 1.6;
    }
    
    .glow-button {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
      transition: all 0.3s ease;
      position: relative;
      overflow: hidden;
    }
    
    .glow-button::before {
      content: '';
      position: absolute;
      top: 0;
      left: -100%;
      width: 100%;
      height: 100%;
      background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
      transition: left 0.5s ease;
    }
    
    .glow-button:hover::before {
      left: 100%;
    }
    
    .glow-button:hover {
      transform: translateY(-2px) scale(1.05);
      box-shadow: 0 15px 40px rgba(102, 126, 234, 0.6);
    }
    
    .fade-in {
      animation: fadeIn 0.8s ease-out;
    }
    
    @keyframes fadeIn {
      from {
        opacity: 0;
        transform: translateY(30px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
    
    .pulse-glow {
      animation: pulseGlow 2s ease-in-out infinite alternate;
    }
    
    @keyframes pulseGlow {
      from {
        box-shadow: 0 0 20px rgba(102, 126, 234, 0.3);
      }
      to {
        box-shadow: 0 0 40px rgba(102, 126, 234, 0.6);
      }
    }
    
    .loading-spinner {
      border: 3px solid rgba(255, 255, 255, 0.3);
      border-radius: 50%;
      border-top: 3px solid #667eea;
      width: 30px;
      height: 30px;
      animation: spin 1s linear infinite;
    }
    
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    
    .favorite-btn {
      transition: all 0.3s ease;
    }
    
    .favorite-btn.active {
      color: #f59e0b;
      transform: scale(1.2);
    }
    
    .share-btn:hover {
      background: rgba(59, 130, 246, 0.1);
      color: #3b82f6;
    }
  </style>
</head>
<body class="gradient-bg min-h-screen flex items-center justify-center relative overflow-hidden">

  <!-- Floating Particles -->
  <div class="floating-particles">
    <!-- Particles will be generated by JavaScript -->
  </div>

  <div class="max-w-4xl mx-auto text-center px-6 relative z-10">
    <!-- Header -->
    <div class="mb-12 fade-in">
      <h1 class="text-6xl font-bold text-white mb-4 drop-shadow-lg">
        ✨ Inspire Me ✨
      </h1>
      <p class="text-xl text-white/80 font-light">
        Discover daily motivation and wisdom to fuel your journey
      </p>
    </div>

    <!-- Quote Card -->
    <div id="quoteCard" class="quote-card rounded-3xl p-12 mb-8 fade-in">
      <div id="loadingSpinner" class="loading-spinner mx-auto mb-4 hidden"></div>
      
      <blockquote id="quoteText" class="quote-text text-3xl font-medium text-gray-800 mb-6 leading-relaxed">
        "Click below to discover your daily dose of inspiration!"
      </blockquote>
      
      <div id="quoteAuthor" class="text-lg text-gray-600 font-medium mb-6">
        <!-- Author will appear here -->
      </div>
      
      <div id="quoteCategory" class="inline-block bg-purple-100 text-purple-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
        <!-- Category will appear here -->
      </div>
      
      <!-- Quote Actions -->
      <div id="quoteActions" class="flex items-center justify-center space-x-4 opacity-0 transition-opacity duration-500">
        <button id="favoriteBtn" class="favorite-btn p-3 rounded-full hover:bg-gray-100 transition-colors" onclick="toggleFavorite()">
          <i class="far fa-heart text-xl"></i>
        </button>
        
        <button class="share-btn p-3 rounded-full hover:bg-gray-100 transition-colors" onclick="shareQuote()">
          <i class="fas fa-share-alt text-xl text-gray-600"></i>
        </button>
        
        <button class="share-btn p-3 rounded-full hover:bg-gray-100 transition-colors" onclick="copyQuote()">
          <i class="fas fa-copy text-xl text-gray-600"></i>
        </button>
      </div>
    </div>

    <!-- Control Buttons -->
    <div class="flex items-center justify-center space-x-6 mb-8">
      <button onclick="generateQuote()" 
              class="glow-button text-white px-8 py-4 rounded-2xl font-semibold text-lg transition-all duration-300 relative overflow-hidden">
        <i class="fas fa-magic mr-2"></i>
        New Inspiration
      </button>
      
      <button onclick="toggleAutoPlay()" 
              id="autoPlayBtn"
              class="bg-white/20 backdrop-blur-sm text-white px-6 py-4 rounded-2xl font-semibold hover:bg-white/30 transition-all duration-300">
        <i class="fas fa-play mr-2"></i>
        Auto Play
      </button>
    </div>

    <!-- Quote Counter -->
    <div class="text-white/70 text-sm">
      <span id="quoteCounter">Quote 1 of 25</span> • 
      <span id="favoriteCounter">0 favorites</span>
    </div>

    <!-- Progress Bar -->
    <div class="w-full bg-white/20 rounded-full h-1 mt-4">
      <div id="progressBar" class="bg-white h-1 rounded-full transition-all duration-300" style="width: 0%"></div>
    </div>
  </div>

  <script>
    const quotes = [
      { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Success" },
      { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon", category: "Wisdom" },
      { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Dreams" },
      { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "Resilience" },
      { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Action" },
      { text: "Don't let yesterday take up too much of today.", author: "Will Rogers", category: "Mindfulness" },
      { text: "You learn more from failure than from success.", author: "Unknown", category: "Growth" },
      { text: "If you are working on something that you really care about, you don't have to be pushed.", author: "Steve Jobs", category: "Passion" },
      { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Confidence" },
      { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Courage" },
      { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "Perseverance" },
      { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Resilience" },
      { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "Authenticity" },
      { text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt", category: "Adventure" },
      { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr.", category: "Friendship" },
      { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness" },
      { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "Simplicity" },
      { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy", category: "Strength" },
      { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa", category: "Love" },
      { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt", category: "Hope" },
      { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson", category: "Progress" },
      { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "Action" },
      { text: "An unexamined life is not worth living.", author: "Socrates", category: "Reflection" },
      { text: "Your limitation—it's only your imagination.", author: "Unknown", category: "Potential" },
      { text: "Great things never come from comfort zones.", author: "Unknown", category: "Growth" }
    ];

    let currentQuoteIndex = 0;
    let favorites = JSON.parse(localStorage.getItem('favoriteQuotes') || '[]');
    let autoPlay = false;
    let autoPlayInterval;

    // Initialize particles
    function createParticles() {
      const particleContainer = document.querySelector('.floating-particles');
      
      for (let i = 0; i < 15; i++) {
        const particle = document.createElement('div');
        particle.className = 'particle';
        particle.style.left = Math.random() * 100 + '%';
        particle.style.width = particle.style.height = Math.random() * 10 + 5 + 'px';
        particle.style.animationDelay = Math.random() * 20 + 's';
        particle.style.animationDuration = (Math.random() * 10 + 15) + 's';
        particleContainer.appendChild(particle);
      }
    }

    function generateQuote() {
      const quoteText = document.getElementById('quoteText');
      const quoteAuthor = document.getElementById('quoteAuthor');
      const quoteCategory = document.getElementById('quoteCategory');
      const quoteActions = document.getElementById('quoteActions');
      const loadingSpinner = document.getElementById('loadingSpinner');
      const favoriteBtn = document.getElementById('favoriteBtn');
      
      // Show loading
      loadingSpinner.classList.remove('hidden');
      quoteActions.style.opacity = '0';
      
      setTimeout(() => {
        const randomIndex = Math.floor(Math.random() * quotes.length);
        const quote = quotes[randomIndex];
        currentQuoteIndex = randomIndex;
        
        // Update content
        quoteText.textContent = `"${quote.text}"`;
        quoteAuthor.textContent = `— ${quote.author}`;
        quoteCategory.textContent = quote.category;
        
        // Update favorite button
        const isFavorite = favorites.some(fav => fav.text === quote.text);
        favoriteBtn.innerHTML = isFavorite ? '<i class="fas fa-heart text-xl"></i>' : '<i class="far fa-heart text-xl"></i>';
        favoriteBtn.classList.toggle('active', isFavorite);
        
        // Hide loading and show actions
        loadingSpinner.classList.add('hidden');
        quoteActions.style.opacity = '1';
        
        // Update counters
        updateCounters();
        updateProgressBar();
        
        // Add animation
        document.getElementById('quoteCard').classList.add('pulse-glow');
        setTimeout(() => {
          document.getElementById('quoteCard').classList.remove('pulse-glow');
        }, 2000);
        
      }, 800);
    }

    function toggleFavorite() {
      const quote = quotes[currentQuoteIndex];
      const favoriteBtn = document.getElementById('favoriteBtn');
      const existingIndex = favorites.findIndex(fav => fav.text === quote.text);
      
      if (existingIndex > -1) {
        favorites.splice(existingIndex, 1);
        favoriteBtn.innerHTML = '<i class="far fa-heart text-xl"></i>';
        favoriteBtn.classList.remove('active');
      } else {
        favorites.push(quote);
        favoriteBtn.innerHTML = '<i class="fas fa-heart text-xl"></i>';
        favoriteBtn.classList.add('active');
      }
      
      localStorage.setItem('favoriteQuotes', JSON.stringify(favorites));
      updateCounters();
    }

    function shareQuote() {
      const quote = quotes[currentQuoteIndex];
      if (navigator.share) {
        navigator.share({
          title: 'Inspiring Quote',
          text: `"${quote.text}" — ${quote.author}`,
          url: window.location.href
        });
      } else {
        copyQuote();
      }
    }

    function copyQuote() {
      const quote = quotes[currentQuoteIndex];
      const text = `"${quote.text}" — ${quote.author}`;
      navigator.clipboard.writeText(text).then(() => {
        showNotification('Quote copied to clipboard! 📋');
      });
    }

    function toggleAutoPlay() {
      const btn = document.getElementById('autoPlayBtn');
      autoPlay = !autoPlay;
      
      if (autoPlay) {
        btn.innerHTML = '<i class="fas fa-pause mr-2"></i>Auto Playing';
        btn.classList.add('bg-green-500/20');
        autoPlayInterval = setInterval(generateQuote, 8000);
        startProgressAnimation();
      } else {
        btn.innerHTML = '<i class="fas fa-play mr-2"></i>Auto Play';
        btn.classList.remove('bg-green-500/20');
        clearInterval(autoPlayInterval);
        document.getElementById('progressBar').style.width = '0%';
      }
    }

    function startProgressAnimation() {
      const progressBar = document.getElementById('progressBar');
      progressBar.style.width = '0%';
      progressBar.style.transition = 'width 8s linear';
      
      setTimeout(() => {
        if (autoPlay) {
          progressBar.style.width = '100%';
        }
      }, 100);
    }

    function updateCounters() {
      document.getElementById('quoteCounter').textContent = `Quote ${currentQuoteIndex + 1} of ${quotes.length}`;
      document.getElementById('favoriteCounter').textContent = `${favorites.length} favorites`;
    }

    function updateProgressBar() {
      const progress = ((currentQuoteIndex + 1) / quotes.length) * 100;
      document.getElementById('progressBar').style.width = progress + '%';
    }

    function showNotification(message) {
      const notification = document.createElement('div');
      notification.className = 'fixed top-4 right-4 bg-white text-gray-800 px-6 py-3 rounded-lg shadow-lg z-50 transform translate-x-full transition-transform duration-300';
      notification.textContent = message;
      document.body.appendChild(notification);
      
      setTimeout(() => {
        notification.style.transform = 'translateX(0)';
      }, 100);
      
      setTimeout(() => {
        notification.style.transform = 'translateX(full)';
        setTimeout(() => {
          document.body.removeChild(notification);
        }, 300);
      }, 3000);
    }

    // Initialize
    document.addEventListener('DOMContentLoaded', function() {
      createParticles();
      updateCounters();
      
      // Auto-generate first quote after a short delay
      setTimeout(generateQuote, 1000);
    });

    // Keyboard shortcuts
    document.addEventListener('keydown', function(e) {
      if (e.code === 'Space') {
        e.preventDefault();
        generateQuote();
      } else if (e.code === 'KeyF') {
        e.preventDefault();
        toggleFavorite();
      } else if (e.code === 'KeyA') {
        e.preventDefault();
        toggleAutoPlay();
      }
    });
  </script>
<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'988cdcd3631d0dc9',t:'MTc1OTQ5ODk0NC4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
